# Generated by Django 4.0.4 on 2022-05-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id producto')),
                ('imagen', models.TextField()),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion del producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
                ('disponible', models.CharField(max_length=1)),
                ('TIPO_PRODUCTO_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de tipo producto')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Nombre del producto')),
            ],
        ),
    ]
